/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author dark_
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/iconoMisOfertas.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMenu = new javax.swing.JLabel();
        jButtonEmpresas = new javax.swing.JButton();
        jButtonProductos = new javax.swing.JButton();
        jButtonDescuentos = new javax.swing.JButton();
        jButtonUsuarios = new javax.swing.JButton();
        jButtonArchivosBi = new javax.swing.JButton();
        jLabelUsuarioIcono1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMenu.setText("Menú Administrador");
        getContentPane().add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jButtonEmpresas.setBackground(new java.awt.Color(204, 255, 255));
        jButtonEmpresas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEmpresas.setText("Mantenedor de Empresas");
        getContentPane().add(jButtonEmpresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 230, 130));

        jButtonProductos.setBackground(new java.awt.Color(204, 255, 255));
        jButtonProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonProductos.setText("Mantenedor de Productos");
        getContentPane().add(jButtonProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 230, 130));

        jButtonDescuentos.setBackground(new java.awt.Color(204, 255, 255));
        jButtonDescuentos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDescuentos.setText("Mantenedor de Descuentos");
        getContentPane().add(jButtonDescuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 230, 120));

        jButtonUsuarios.setBackground(new java.awt.Color(204, 255, 255));
        jButtonUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUsuarios.setText("Mantenedor de Usuarios");
        getContentPane().add(jButtonUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 230, 120));

        jButtonArchivosBi.setBackground(new java.awt.Color(204, 255, 255));
        jButtonArchivosBi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonArchivosBi.setText("Archivos BI");
        getContentPane().add(jButtonArchivosBi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 230, 130));

        jLabelUsuarioIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user2.png"))); // NOI18N
        getContentPane().add(jLabelUsuarioIcono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FondoWhite.jpg"))); // NOI18N
        jLabelFondo.setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArchivosBi;
    private javax.swing.JButton jButtonDescuentos;
    private javax.swing.JButton jButtonEmpresas;
    private javax.swing.JButton jButtonProductos;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelUsuarioIcono1;
    // End of variables declaration//GEN-END:variables
}
